# Generated by Django 2.2.5 on 2019-10-22 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('vacationMonthDayBegin', models.IntegerField(default=0)),
                ('vacationMonthDayEnd', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('deliveredSuccessfully', models.BooleanField(default=False)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentportal.Customer')),
                ('newsAgentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentportal.NewsAgent')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentportal.NewsAgent'),
        ),
    ]
