# Generated by Django 2.2.5 on 2019-10-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentportal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsAgent',
            new_name='Agent',
        ),
    ]
