# Generated by Django 2.2.5 on 2019-10-22 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentportal', '0002_auto_20191022_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='newsAgentID',
            new_name='agentID',
        ),
    ]
