# Generated by Django 2.2.5 on 2019-10-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentportal', '0003_auto_20191022_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='agentID',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='customerID',
            new_name='customer',
        ),
    ]
