# Generated by Django 2.2.5 on 2019-11-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentportal', '0005_auto_20191113_0339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='agent',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='agent',
            new_name='user',
        ),
    ]
